# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myproject.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(631, 442)
        Dialog.setStyleSheet("")
        self.myButton = QtWidgets.QPushButton(Dialog)
        self.myButton.setGeometry(QtCore.QRect(220, 290, 101, 27))
        self.myButton.setObjectName("myButton")
        self.NameField = QtWidgets.QLineEdit(Dialog)
        self.NameField.setGeometry(QtCore.QRect(180, 110, 171, 31))
        self.NameField.setObjectName("NameField")
        self.AgeField = QtWidgets.QLineEdit(Dialog)
        self.AgeField.setGeometry(QtCore.QRect(180, 170, 171, 31))
        self.AgeField.setObjectName("AgeField")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(210, 20, 161, 51))
        self.title.setObjectName("title")
        self.NameLabel = QtWidgets.QLabel(Dialog)
        self.NameLabel.setGeometry(QtCore.QRect(400, 110, 41, 31))
        self.NameLabel.setObjectName("NameLabel")
        self.AgeLabel = QtWidgets.QLabel(Dialog)
        self.AgeLabel.setGeometry(QtCore.QRect(385, 170, 51, 20))
        self.AgeLabel.setObjectName("AgeLabel")
        self.GenLabel = QtWidgets.QLabel(Dialog)
        self.GenLabel.setGeometry(QtCore.QRect(385, 230, 51, 31))
        self.GenLabel.setObjectName("GenLabel")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(180, 230, 171, 31))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.StateLabel = QtWidgets.QLabel(Dialog)
        self.StateLabel.setGeometry(QtCore.QRect(140, 360, 201, 41))
        self.StateLabel.setStyleSheet("")
        self.StateLabel.setObjectName("StateLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.myButton.setText(_translate("Dialog", "تسجيل"))
        self.title.setText(_translate("Dialog", "أهلا وسهلا في موقعنا الأول"))
        self.NameLabel.setText(_translate("Dialog", "الأسم"))
        self.AgeLabel.setText(_translate("Dialog", "السن"))
        self.GenLabel.setText(_translate("Dialog", "النوع"))
        self.comboBox.setItemText(0, _translate("Dialog", "اختر من القائمة"))
        self.comboBox.setItemText(1, _translate("Dialog", "Male"))
        self.comboBox.setItemText(2, _translate("Dialog", "Female"))
        self.StateLabel.setText(_translate("Dialog", "من فضلك أدخل بياناتك"))
